#!/usr/bin/env python

import sys
from worker import *
import argparse

# parser = argparse.ArgumentParser(description='Process some integers.')
# parser.add_argument('integers', metavar='N', type=int, nargs='+',
#                    help='an integer for the accumulator')
# parser.add_argument('--sum', dest='accumulate', action='store_const',
#                    const=sum, default=max,
#                    help='sum the integers (default: find the max)')

# args = parser.parse_args()
# print(args.accumulate(args.integers))

def main():
    worker = TaasWorker(
            couchdb_host = "localhost",
            couchdb_port = 8080,
            amqp_host = "localhost",
            amqp_port = 5672,
            amqp_queue="taas.test_queue"
            )
    worker.run_forever()

if __name__ == '__main__':
    main()
